### ISSUE TITLE
Peculiarities of input

### ISSUE THREAD

**Issue by flbmld** [byru55o/r5steg#3]
Hello. I noticed that I can't use ← and → arrows or other keyboard shortcuts to move. When I type text (secret or text) and press the arrows, the characters `^[[D` and `^[[C` but the move doesn't happen. This is frustrating because I need to copy the text before the error, delete it then correct the error and paste the copied text. Is this a feature of the input or some kind of bug, and is there anything we can do about it?

Thanks for your reply.

**Comment by byru55o** [comment]
Hello!
The echoed escape characters such as `^[[D` are expected in python inputs. However, I always found them frustrating also (even more in other programs of mine). So I investigated a little bit and came to [this library](https://docs.python.org/3/library/readline.html). It works really nice and also offers history and more shortcuts such as in your regular terminal. I'm definitely importing it in r5steg, thank you.

**Comment by flbmld** [comment]
Many thanks! Much more comfortable ^^
