### ISSUE TITLE
[Question] Configuration file & colours

### ISSUE THREAD

**Issue by SilentoA** [byru55o/r5steg#8]
Hi!

After using r5steg for a long time, it became more difficult to focus on the right lines, because they are all the same color.

What do you think about this? Maybe we need to add other colors for the output lines?

**Comment by SilentoA** [comment]
The truth is that you have to set the color on a separate line, because otherwise L10n will not work.

L10n does not work here:

```
red     = "\033[0;31m"
print(_(red + "Red text"))
```
Everything will work here:

```
red     = "\033[0;31m"
print(red)
print(_("Red text"))

```

**Comment by SilentoA** [comment]
Finding the right colors turned out to be much more difficult than I thought. On dark and light themes, these colors are perceived differently, so I couldn't reach a compromise... Therefore, the question is (temporarily?) closed. However, I am ready to return to it in the future, if I can still find the right ones.

**Comment by byru55o** [comment]
If you come up with a good combination of colours it would be great. Also, a different approach is to let the user customize them if he doesn't like them through a config file.

**Comment by SilentoA** [comment]
The config file is redundant for two or three colors. I'll see what can be done.

**Comment by s0ck37** [comment]
A config file would be more organized, making the end user modify the source code for changing color preferences is not the ideal way to go. Also this opens the door for colors profiles for specific themes such as nord, onedark, etc.
Also the config file can be used to custom some parameters such as: turning on and off encryption, chaning the utf chars,... 
[This library](https://docs.python.org/3/library/configparser.html) can provide an easy and organized way to do this, and should be installed with native python.

**Comment by SilentoA** [comment]
I think a separate option is needed to use/not use encryption for a message.

**Comment by byru55o** [comment]
@s0ck37 
> A config file would be more organized, making the end user modify the source code for changing color preferences is not the ideal way to go. Also this opens the door for colors profiles for specific themes such as nord, onedark, etc. Also the config file can be used to custom some parameters such as: turning on and off encryption, chaning the utf chars,... [This library](https://docs.python.org/3/library/configparser.html) can provide an easy and organized way to do this, and should be installed with native python.

That might be a good thing to do, especially if I want to add colors, but making it easier for the user to change other parameters is also a big advantage. I have looked into the configparser library and I really like the syntax it provides.

Also, @SilentoA is right, I removed the code snippet for normal text-to-hex conversion, since the AES function does it anyway. However, I think it could be a good idea to add it again because some users may prioritize a shorter hidden message over encryption.

**Comment by byru55o** [comment]
I have the pleasure to announce that **configuration through an INI file and colours are now avaliable** in r5steg.
Thanks for the feedback and suggestions @SilentoA @s0ck37 . Check the readme file for further information.
